apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: "docker/default" 
    or: 
    seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
  labels:
    app: nginx
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsUser: 2000
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME"]
              drop: ["ALL"]
          ports:
            - containerPort: 80
